<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_searchValue</name>
   <tag></tag>
   <elementGuidId>a27aefcc-dc3f-4cad-abeb-2efeebdea1cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;search&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31c8cf20-5276-4f2c-92b3-38fe21edfddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5a535a0-4ed4-4000-80a5-419ff00dca2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>70f83028-8ee3-4908-8423-02c756e77253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autocomplete</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ba85b5f3-80e9-4080-b2bd-7db72ea4764e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autocomplete_route</name>
      <type>Main</type>
      <value>extension/maza/product/product/autocomplete</value>
      <webElementGuid>9abd7921-7938-48f7-ad1e-ccb85e7949c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search For Products</value>
      <webElementGuid>72882fec-bbfd-41a0-95bf-6877c6b60633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search For Products</value>
      <webElementGuid>1ea4886d-4a6c-4d5b-8f58-95ba2219f64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>513794a0-706d-4a09-aea4-ca19c0dcc484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entry_217822&quot;)/div[@class=&quot;search-wrapper&quot;]/form[1]/div[@id=&quot;search&quot;]/div[@class=&quot;search-input-group flex-fill&quot;]/div[@class=&quot;search-input d-flex&quot;]/div[@class=&quot;flex-fill&quot;]/input[1]</value>
      <webElementGuid>39440f9c-60e9-42ed-ab5f-6b592bc3c417</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='search']</value>
      <webElementGuid>49cec141-39c3-4050-b7ee-12860d2e5fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div[2]/input</value>
      <webElementGuid>56f64a14-02a4-4822-b505-8ece826ec65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4c68bb31-0056-48ba-bd19-52f4e0197691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search' and @placeholder = 'Search For Products']</value>
      <webElementGuid>9a5addbd-f594-41e3-bdda-0c0a52dc5e93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
