<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_userMessage</name>
   <tag></tag>
   <elementGuidId>e90e42a4-ab6e-49cd-8883-4fec1b04a0b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='entry_217838']/p/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.m-0.font-size-sm > strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>5902065e-8c10-467a-bf7e-9f2c2e2307c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is a dummy website for Web Automation Testing</value>
      <webElementGuid>b24b7734-eed6-4c55-b83e-7750f2821c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entry_217838&quot;)/p[@class=&quot;m-0 font-size-sm&quot;]/strong[1]</value>
      <webElementGuid>fe64b53f-a0a4-4e2f-815e-02cd3ffd81f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entry_217838']/p/strong</value>
      <webElementGuid>b7224f89-fb80-4be3-a262-7703fce223b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Categories'])[3]/following::strong[1]</value>
      <webElementGuid>1473ed84-fc02-4a89-9092-df9aab2a409c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::strong[1]</value>
      <webElementGuid>f4b5f52a-8fdd-401b-b9e2-3dc9e384122e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upto 60% Off'])[1]/preceding::strong[1]</value>
      <webElementGuid>26654c04-87b8-4081-8fb0-838842aef82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This is a dummy website for Web Automation Testing']/parent::*</value>
      <webElementGuid>0d66f305-507d-4fa7-a27d-8036d568935d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/strong</value>
      <webElementGuid>12cf573d-d374-4d40-99e5-382cb7255c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'This is a dummy website for Web Automation Testing' or . = 'This is a dummy website for Web Automation Testing')]</value>
      <webElementGuid>4685d96e-f37a-46e6-bdb2-9c91d36d9720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
