<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_resultsCount</name>
   <tag></tag>
   <elementGuidId>4f276565-c2b4-4716-8340-e819dc54094c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='entry_212470']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-6.text-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e80a9a27-f831-4183-934f-067a6c674a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-6 text-right</value>
      <webElementGuid>9efc5e35-4cea-4eaa-ac5b-303f781dcab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Showing 1 to 6 of 6 (1 Pages)</value>
      <webElementGuid>7e419ebe-711a-4f14-b7e8-1f9075560724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entry_212470&quot;)/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-sm-6 text-right&quot;]</value>
      <webElementGuid>5c6fa35d-9a14-4ba5-91d3-2387a1b5ba2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entry_212470']/div/div[2]</value>
      <webElementGuid>cc494020-5cad-4cd8-ab25-4050a4b0ddd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,000.00'])[2]/following::div[4]</value>
      <webElementGuid>9a80c384-e32c-402f-bc4a-bbd34555ba3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MacBook Pro'])[2]/following::div[5]</value>
      <webElementGuid>25f363a0-14b9-4b11-a385-f7b9b29f5d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[2]/preceding::div[1]</value>
      <webElementGuid>c3349a8e-1f02-468b-85e3-0fb84801f22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[2]/preceding::div[2]</value>
      <webElementGuid>d368c073-32ce-4a21-acce-399f92a09082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Showing 1 to 6 of 6 (1 Pages)']/parent::*</value>
      <webElementGuid>c1306400-8d9b-4b09-a229-34b8bef9ad17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[6]/div/div[2]</value>
      <webElementGuid>a66ad4bc-d828-40c0-83af-0904b54c239e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Showing 1 to 6 of 6 (1 Pages)' or . = 'Showing 1 to 6 of 6 (1 Pages)')]</value>
      <webElementGuid>2b09ce41-d90c-4142-9b41-8818a6c61d39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
